name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass  # Установка утилиты sshpass

      - name: Stop pm2 processes on server
        run: |
          sshpass -p "${{ snatcher.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ snatcher.SERVER_IP }} "pm2 stop all"  # Останавливаем все процессы через pm2 под root

      - name: Deploy new code to server
        run: |
          sshpass -p "${{ snatcher.SSH_PASSWORD }}" scp -r ./ root@${{ snatcher.SERVER_IP }}:~/dialog  # Копируем новые файлы на сервер

      - name: Start pm2 processes on server
        run: |
          sshpass -p "${{ snatcher.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ snatcher.SERVER_IP }} "cd ~/dialog && pm2 start all"  # Запускаем все процессы через pm2 под root
